version: '3.5'
services:
  playground-postgres:
    container_name: playground-postgres
    image: jbkoh/brickserver-postgresql:latest
    environment: # Below secrets should be matched with the information in `.env` too.
      - POSTGRES_USER=bricker
      - POSTGRES_PASSWORD=brick-demo
      - POSTGRES_DB=brick
    networks:
      - playground-backend-network
    ports:
      - "35432:5432"
  playground-virtuoso:
    container_name: playground-virtuoso
    image: tenforce/virtuoso:virtuoso7.2.5
    environment:
      - SPARQL_UPDATE=true
    networks:
      - playground-backend-network
    ports:
      - "38890:8890"
  playground-graphdb:
    container_name: playground-graphdb
    image: w1zzard/graphdb-free:9.9.0
    networks:
      - playground-backend-network
    ports:
      - "37200:7200"
  playground-mongo:
    container_name: playground-mongo
    image: mongo:4.2.3-bionic
    networks:
      - playground-backend-network
    ports:
      - "37017:27017"
  playground-redis:
    container_name: playground-redis
    image: 'redis:5.0.8'
    command: redis-server --requirepass brick-demo
    networks:
      - playground-backend-network
    ports:
      - "36379:6379"
#  playground:
#    container_name: playground
#    image: brick_server
#    volumes:
#      - ./brick_server:/root/brick_server
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - "9000:9000"
#    networks:
#      - playground-backend-network
#      - isolated_nw
#    environment:
#      - DEBUG=true
#      - HOST=playground
#      - MONGO_HOST=playground-mongo
#      - LOCKMANAGER_HOST=playground-postgres
#      - TIMESCALE_HOST=playground-postgres
#      - BRICK_HOST=playground-virtuoso
##      - GRAFANA_HOST=playground-grafana
#    privileged: true
##    entrypoint: /app/docker/start-reload.sh

networks:
  playground-backend-network:
  isolated_nw:
