[tool.poetry]
name = "brick-server-backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
packages = [
    { include = "brick_server" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
fastapi = "^0.68.1"
pyparsing = "2.3.1"
brick-data = {git = "https://github.com/jbkoh/brick_data.git", rev = "master"}
httpx = "0.12.0"
aiosparql = "^0.12.0"
arrow = "^1.1.1"
asyncpg = "^0.24.0"
Authlib = "^0.15.4"
fastapi-utils = "^0.2.1"
jedi = "^0.18.0"
mongoengine = "^0.23.1"
numpy = "^1.21.2"
pandas = "^1.3.3"
psycopg2-binary = "^2.9.1"
pydantic = "^1.8.2"
PyJWT = "^2.1.0"
pytest = "^6.2.5"
PyYAML = "^5.4.1"
rdflib = "^4.2.2"
redis = "^3.5.3"
requests = "^2.26.0"
uvicorn = "^0.15.0"
Werkzeug = "^2.0.1"
itsdangerous = "^2.0.1"
docker = "^5.0.2"
protobuf = "^3.17.3"
grpcio = "^1.40.0"
aiofiles = "^0.7.0"
pytest-env = "^0.6.2"
pytest-ordering = "^0.6"
fastapi-rest-framework = {git = "https://github.com/joint-online-judge/fastapi-rest-framework", rev = "master"}
timeout-decorator = "^0.5.0"
python-multipart = "^0.0.5"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"

[tool.poetry.extras]
test = [
    "pytest",
    "pytest-env",
    "pytest-ordering",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
