# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuation_server.proto
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    message as _message,
    reflection as _reflection,
    symbol_database as _symbol_database,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="actuation_server.proto",
    package="actuationserver",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x16\x61\x63tuation_server.proto\x12\x0f\x61\x63tuationserver"/\n\x0bSensorValue\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02"(\n\x06Status\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2\xb4\x01\n\x0f\x41\x63tuationServer\x12N\n\x13\x41\x63tuateSingleSensor\x12\x1c.actuationserver.SensorValue\x1a\x17.actuationserver.Status"\x00\x12Q\n\x12\x41\x63tuateMultiSensor\x12\x1c.actuationserver.SensorValue\x1a\x17.actuationserver.Status"\x00(\x01\x30\x01\x62\x06proto3',
)


_SENSORVALUE = _descriptor.Descriptor(
    name="SensorValue",
    full_name="actuationserver.SensorValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="sensor_id",
            full_name="actuationserver.SensorValue.sensor_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="actuationserver.SensorValue.value",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=43,
    serialized_end=90,
)


_STATUS = _descriptor.Descriptor(
    name="Status",
    full_name="actuationserver.Status",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="result",
            full_name="actuationserver.Status.result",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="detail",
            full_name="actuationserver.Status.detail",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=92,
    serialized_end=132,
)

DESCRIPTOR.message_types_by_name["SensorValue"] = _SENSORVALUE
DESCRIPTOR.message_types_by_name["Status"] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorValue = _reflection.GeneratedProtocolMessageType(
    "SensorValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _SENSORVALUE,
        "__module__": "actuation_server_pb2"
        # @@protoc_insertion_point(class_scope:actuationserver.SensorValue)
    },
)
_sym_db.RegisterMessage(SensorValue)

Status = _reflection.GeneratedProtocolMessageType(
    "Status",
    (_message.Message,),
    {
        "DESCRIPTOR": _STATUS,
        "__module__": "actuation_server_pb2"
        # @@protoc_insertion_point(class_scope:actuationserver.Status)
    },
)
_sym_db.RegisterMessage(Status)


_ACTUATIONSERVER = _descriptor.ServiceDescriptor(
    name="ActuationServer",
    full_name="actuationserver.ActuationServer",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=135,
    serialized_end=315,
    methods=[
        _descriptor.MethodDescriptor(
            name="ActuateSingleSensor",
            full_name="actuationserver.ActuationServer.ActuateSingleSensor",
            index=0,
            containing_service=None,
            input_type=_SENSORVALUE,
            output_type=_STATUS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="ActuateMultiSensor",
            full_name="actuationserver.ActuationServer.ActuateMultiSensor",
            index=1,
            containing_service=None,
            input_type=_SENSORVALUE,
            output_type=_STATUS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ACTUATIONSERVER)

DESCRIPTOR.services_by_name["ActuationServer"] = _ACTUATIONSERVER

# @@protoc_insertion_point(module_scope)
