# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuation_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61\x63tuation_server.proto\x12\x0f\x61\x63tuationserver\"/\n\x0bSensorValue\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\x06Status\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2\xb4\x01\n\x0f\x41\x63tuationServer\x12N\n\x13\x41\x63tuateSingleSensor\x12\x1c.actuationserver.SensorValue\x1a\x17.actuationserver.Status\"\x00\x12Q\n\x12\x41\x63tuateMultiSensor\x12\x1c.actuationserver.SensorValue\x1a\x17.actuationserver.Status\"\x00(\x01\x30\x01\x62\x06proto3')



_SENSORVALUE = DESCRIPTOR.message_types_by_name['SensorValue']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
SensorValue = _reflection.GeneratedProtocolMessageType('SensorValue', (_message.Message,), {
  'DESCRIPTOR' : _SENSORVALUE,
  '__module__' : 'actuation_server_pb2'
  # @@protoc_insertion_point(class_scope:actuationserver.SensorValue)
  })
_sym_db.RegisterMessage(SensorValue)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'actuation_server_pb2'
  # @@protoc_insertion_point(class_scope:actuationserver.Status)
  })
_sym_db.RegisterMessage(Status)

_ACTUATIONSERVER = DESCRIPTOR.services_by_name['ActuationServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORVALUE._serialized_start=43
  _SENSORVALUE._serialized_end=90
  _STATUS._serialized_start=92
  _STATUS._serialized_end=132
  _ACTUATIONSERVER._serialized_start=135
  _ACTUATIONSERVER._serialized_end=315
# @@protoc_insertion_point(module_scope)
