# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import brick_server.minimal.interfaces.actuation.metasys.actuate_pb2 as actuate__pb2


class ActuateStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TemporaryOverride = channel.unary_unary(
            "/Actuate/TemporaryOverride",
            request_serializer=actuate__pb2.TemporaryOverrideAction.SerializeToString,
            response_deserializer=actuate__pb2.Response.FromString,
        )


class ActuateServicer:
    """Missing associated documentation comment in .proto file."""

    def TemporaryOverride(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ActuateServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TemporaryOverride": grpc.unary_unary_rpc_method_handler(
            servicer.TemporaryOverride,
            request_deserializer=actuate__pb2.TemporaryOverrideAction.FromString,
            response_serializer=actuate__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Actuate", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Actuate:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TemporaryOverride(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Actuate/TemporaryOverride",
            actuate__pb2.TemporaryOverrideAction.SerializeToString,
            actuate__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
