# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

import brick_server.minimal.interfaces.actuation.metasys.actuate_pb2 as actuate__pb2

GRPC_GENERATED_VERSION = "1.63.0"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in actuate_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class ActuateStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TemporaryOverride = channel.unary_unary(
            "/Actuate/TemporaryOverride",
            request_serializer=actuate__pb2.TemporaryOverrideAction.SerializeToString,
            response_deserializer=actuate__pb2.Response.FromString,
            _registered_method=True,
        )
        self.ReadObjectCurrent = channel.unary_unary(
            "/Actuate/ReadObjectCurrent",
            request_serializer=actuate__pb2.ReadObjectCurrentAction.SerializeToString,
            response_deserializer=actuate__pb2.Response.FromString,
            _registered_method=True,
        )


class ActuateServicer:
    """Missing associated documentation comment in .proto file."""

    def TemporaryOverride(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadObjectCurrent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ActuateServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TemporaryOverride": grpc.unary_unary_rpc_method_handler(
            servicer.TemporaryOverride,
            request_deserializer=actuate__pb2.TemporaryOverrideAction.FromString,
            response_serializer=actuate__pb2.Response.SerializeToString,
        ),
        "ReadObjectCurrent": grpc.unary_unary_rpc_method_handler(
            servicer.ReadObjectCurrent,
            request_deserializer=actuate__pb2.ReadObjectCurrentAction.FromString,
            response_serializer=actuate__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Actuate", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Actuate:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TemporaryOverride(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Actuate/TemporaryOverride",
            actuate__pb2.TemporaryOverrideAction.SerializeToString,
            actuate__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadObjectCurrent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Actuate/ReadObjectCurrent",
            actuate__pb2.ReadObjectCurrentAction.SerializeToString,
            actuate__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
