# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuate.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ractuate.proto":\n\x17ReadObjectCurrentAction\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\tattribute\x18\x02 \x01(\t"\x9a\x01\n\x17TemporaryOverrideAction\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\x04hour\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x13\n\x06minute\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x17\n\nannotation\x18\x05 \x01(\tH\x02\x88\x01\x01\x42\x07\n\x05_hourB\t\n\x07_minuteB\r\n\x0b_annotation"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2\x81\x01\n\x07\x41\x63tuate\x12:\n\x11TemporaryOverride\x12\x18.TemporaryOverrideAction\x1a\t.Response"\x00\x12:\n\x11ReadObjectCurrent\x12\x18.ReadObjectCurrentAction\x1a\t.Response"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "actuate_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_READOBJECTCURRENTACTION"]._serialized_start = 17
    _globals["_READOBJECTCURRENTACTION"]._serialized_end = 75
    _globals["_TEMPORARYOVERRIDEACTION"]._serialized_start = 78
    _globals["_TEMPORARYOVERRIDEACTION"]._serialized_end = 232
    _globals["_RESPONSE"]._serialized_start = 234
    _globals["_RESPONSE"]._serialized_end = 277
    _globals["_ACTUATE"]._serialized_start = 280
    _globals["_ACTUATE"]._serialized_end = 409
# @@protoc_insertion_point(module_scope)
