#!/usr/bin/env bash

openssl req -newkey rsa:4096 \
            -x509 \
            -sha256 \
            -days 3650 \
            -nodes \
            -out configs/grafana/brickserver.crt \
            -keyout configs/grafana/brickserver.key
