#!/usr/bin/env python

import sys
import jwt
from pdb import set_trace as bp
import arrow
sys.path.append("./")

from brick_server.auth.authorization import FRONTEND_APP
from brick_server.models import User

if len(sys.argv) == 2:
    user_id = sys.argv[1]
elif len(sys.argv) == 1:
    user_id = 'admin'
else:
    raise Exception('too many parameters are given')


users = User.objects(user_id=user_id)
if not users:
    user = User(
        user_id=user_id,
        name=user_id,
        is_admin=True,
        is_approved=True,
        registration_time=arrow.get().datetime,
        email=user_id,
        activated_apps=[],
    )
    user.save()
else:
    user = users[0]
    user.is_admin = True
    user.save()

